const weeks=[
['认识大模型','💬','pink','做出第一版 AI 对话',[['理解 LLM、Token 与上下文','知道模型如何读懂和生成文字','概念'],['用 Node.js 完成首次模型调用','密钥放入环境变量，不写进代码','动手'],['实现多轮对话与历史消息','让助手能记住当前会话','Node.js'],['Vue 实现流式输出','加入停止、重试和错误提示','Vue']]],
['工具调用','🧰','peach','让 AI 不只会聊天',[['掌握结构化 JSON 输出','用 Schema 校验模型结果','基础'],['实现 Function Calling','制作计算器或天气查询工具','AI 工具'],['保存会话到数据库','支持新建、删除和重命名','全栈'],['发布 AI 聊天助手 v1','补齐说明文档并录制演示','作品']]],
['Python 快速入门','🐍','mint','用熟悉的 JS 思维学 Python',[['掌握 Python 核心语法','列表、字典、函数与类型标注','Python'],['文件、JSON 与 HTTP 请求','完成三个小练习','Python'],['理解包和虚拟环境','能独立运行一个 Python 项目','环境'],['用 Python 调用大模型','重写已有 Node.js 调用','迁移']]],
['FastAPI 服务','⚡','blue','做出可用的 Python AI 服务',[['学习 FastAPI 与 Pydantic','编写带类型校验的接口','后端'],['实现异步与流式响应','Vue 前端接入 Python 服务','全栈'],['连接数据库并处理异常','补充日志和友好报错','工程'],['完成基础接口测试','为关键接口写 pytest','测试']]],
['RAG 起步','📚','purple','让 AI 阅读你的资料',[['理解 Embedding 与向量检索','能解释语义相似度','RAG'],['完成文档解析与切分','支持 PDF、Markdown、TXT','数据'],['接入向量数据库','保存并检索文本片段','数据库'],['完成最小知识库问答','回答中展示引用来源','作品']]],
['提升检索质量','🔎','yellow','让知识库答得更准',[['实现混合检索','结合关键词与向量结果','检索'],['增加重排序','比较加入前后的命中效果','优化'],['处理无答案问题','没有证据时明确拒答','可靠性'],['准备 30 条评测问题','标记每题对应的正确资料','评测']]],
['RAG 产品化','🏡','mint','完成电商知识助手',[['制作知识库管理页面','上传、查看和删除文档','Vue'],['记录命中率、延迟和成本','形成真实的评测报告','指标'],['完成用户与权限功能','不同知识库相互隔离','产品'],['发布企业知识助手 v1','补齐架构图和演示视频','里程碑']]],
['Agent 入门','🤖','blue','让 AI 主动使用工具',[['理解 Agent 执行循环','计划、行动、观察与修正','Agent'],['封装库存与订单工具','定义清晰的参数 Schema','工具'],['实现多步骤工具调用','记录每一步的输入与结果','流程'],['增加人工确认节点','重要写操作必须先确认','安全']]],
['电商运营 Agent','🛍️','pink','完成第二个核心作品',[['加入 CSV 销售分析工具','识别销量趋势和低库存商品','数据'],['加入文案与工单工具','生成内容并创建待办','自动化'],['处理超时、重试与重复执行','保证任务失败后可恢复','稳定性'],['完成 Agent 评测与演示','记录成功率和典型失败案例','作品']]],
['补齐 AI 原理','🧠','purple','面试时能讲明白',[['理解训练、微调与推理','知道三者的成本和用途','原理'],['理解 Transformer 与 Attention','能用自己的话解释','原理'],['理解 LoRA、量化与开源模型','知道什么时候应该使用','模型'],['整理 20 道 AI 面试题','每题写出自己的答案','面试']]],
['部署与工程化','🚀','peach','让作品像真实产品',[['使用 Docker Compose 部署','一条指令启动完整项目','部署'],['增加缓存、限流与降级','模型故障时仍有友好反馈','稳定性'],['加入日志与调用追踪','能够定位一次错误请求','可观测'],['完成线上部署','邀请朋友实际体验并反馈','上线']]],
['求职冲刺','🏆','yellow','开始投递杭州 AI 岗位',[['整理 3 个作品项目','每个都有说明、架构图和演示','作品集'],['完成 AI 方向简历','用真实指标描述项目成果','简历'],['进行 2 次模拟面试','记录并修补知识盲区','面试'],['投递首批 20 个岗位','重点关注滨江、余杭和西湖','杭州']]]
];
const key='ai-path-hangzhou-progress-v1';let done=[];try{done=JSON.parse(localStorage.getItem(key)||'[]')}catch{}let filter='all';
const grid=document.querySelector('#weeksGrid');
function render(){grid.innerHTML='';weeks.forEach((w,wi)=>{const tasks=w[4].map((t,ti)=>({t,id:`w${wi+1}-${ti+1}`}));const visible=tasks.filter(x=>filter==='all'||(filter==='done'?done.includes(x.id):!done.includes(x.id)));if(!visible.length&&filter!=='all')return;const count=tasks.filter(x=>done.includes(x.id)).length;const el=document.createElement('article');el.className=`week ${w[2]}`;el.innerHTML=`<div class="week-head"><div class="emoji">${w[1]}</div><article><small>WEEK ${String(wi+1).padStart(2,'0')}</small><h3>${w[0]}</h3></article><span class="count">${count}/4</span></div><p class="goal">本周目标 · ${w[3]}</p><div>${visible.map(x=>`<label class="task ${done.includes(x.id)?'done':''}" data-id="${x.id}"><input type="checkbox" ${done.includes(x.id)?'checked':''}><span class="check">✓</span><span class="copy"><b>${x.t[0]}</b><small>${x.t[1]}</small></span><span class="tag">${x.t[2]}</span></label>`).join('')}</div><div class="meter"><span style="width:${count*25}%"></span></div>`;grid.appendChild(el)});document.querySelectorAll('.task').forEach(el=>el.onclick=()=>toggle(el.dataset.id));update()}
function toggle(id){done=done.includes(id)?done.filter(x=>x!==id):[...done,id];localStorage.setItem(key,JSON.stringify(done));render()}
function update(){const n=done.length,p=Math.round(n/48*100),cw=weeks.findIndex((_,i)=>[1,2,3,4].some(j=>!done.includes(`w${i+1}-${j}`)))+1;document.querySelector('#percent').textContent=p+'%';document.querySelector('#done').textContent=n;document.querySelector('#weeks').textContent=Math.floor(n/4);document.querySelector('#totalBar').style.width=p+'%';document.querySelector('#ring').style.background=`conic-gradient(#ff789c ${p*3.6}deg,#f1ece6 0)`;document.querySelector('#currentWeek').textContent=`第 ${cw||12} 周`;document.querySelector('#mascot').textContent=p===100?'🦄':p>=70?'🚀':p>=35?'🐥':'🥚';document.querySelector('#cheer').textContent=p===100?'你毕业啦！':p?'今天也有进步！':'一起出发吧！';document.querySelector('#progressText').textContent=n===0?'完成第一项任务，让旅程开始吧。':n===48?'全部完成！现在带着作品去闪闪发光吧。':`已经收集 ${n} 颗成长星星，继续保持！`}
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelector('#reset').onclick=()=>{if(confirm('确定要清空所有学习进度吗？')){done=[];localStorage.removeItem(key);render()}};render();
